### ISSUE TITLE
Build Fail: failed to parse the version requirement '' for dependency 'gio'

### ISSUE THREAD

**Issue by yemouu** [VixenUtils/Myxer#18]
When running `cargo build --release`, the build fails with this message.
```
error: failed to parse manifest at `/home/mou/tmp/ebuild-temp/Myxer-1.2.1/Cargo.toml`

Caused by:
  failed to parse the version requirement `` for dependency `gio`

Caused by:
  unexpected end of input while parsing major version number
  ```

**Comment by MikaelUrankar** [comment]
You need to put the version in Cargo.toml:
```
--- Cargo.toml.orig
+++ Cargo.toml
@@ -36,5 +36,5 @@ version = "0.9.0"
 features = [ "v3_22" ]
 
 [dependencies.gio]
-version = ""
+version = "0.9.1"
 features = [ "v2_44" ]
```

https://github.com/VixenUtils/Myxer/blob/master/Cargo.lock#L250

**Comment by ErinvanderVeen** [comment]
PR reopened at #20

**Comment by bneijt** [comment]
Tried to install this from aur source and ran into this issue on Archlinux.

My workaround was
- download https://aur.archlinux.org/packages/myxer
- extract, run `makepkg` which will fail on the gio dependency
- update the file `src/Myxer-1.2.1/Cargo.toml` as per PR suggested
- run `makepkg -e` to build without extracting the source again.

When this is merged, please consider publishing a new release.

**Comment by Aurailus** [comment]
Thank you! I know this is very late but I've merged this :)
