### ISSUE TITLE
Happy but....

### ISSUE THREAD

**Issue by jurgynet** [VixenUtils/Myxer#25]
I am very happy with the simplicity and functionality.... esp compared to pavucontrol.
but I wish I could drag it to be much much smaller...  What about no slider, and/or mouse wheel on the vol % also adjusts it.
your thoughts?

**Comment by Aurailus** [comment]
Hey there, this would be an interesting feature. Unfortunately, I don't have time to implement it, however if you create a pull request I'd be happy to merge it :) Feel free to reopen if you are interested.
