### ISSUE TITLE
Option to combine Input and Output pages?

### ISSUE THREAD

**Issue by mxmilkiib** [VixenUtils/Myxer#26]
I think this would be very handy, if you ever have time to revisit the project! Thanks for the app as it stands though!

**Comment by Aurailus** [comment]
How would this work? Would there be any sort of divider or would it just all be merged? If so, how would you distinguish what is an input and what is an output?

**Comment by mxmilkiib** [comment]
I guess a basic graphical divider might be the easiest option, with Input and Output channels being aligned to the left and right respectively?

Currently I use [pavucontrol-compact](https://aur.archlinux.org/packages/pavucontrol-compact-git) which is styled like this, though it's not quite analagous but I thought I'd mention it. 

![image](https://github.com/VixenUtils/Myxer/assets/108225/f4dd9acc-1864-407f-8ea8-8ebf98dd63a7)

I've also used JACK Mixer, but that's a much mre manual form of setup.

![image](https://github.com/VixenUtils/Myxer/assets/108225/40b633b0-d7db-4973-83d6-ee7bc9cd7c83)

There's also KMix;

![image](https://github.com/VixenUtils/Myxer/assets/108225/dff6b4ec-e826-4f0b-a960-6dbfd6595338)

**Comment by Aurailus** [comment]
I see, thank you for the additional information. Unfortunately, I don't have time to implement this right now, however if you create a pull request with the feature, I'd be happy to merge it :) Feel free to reopen if you are interested.
