### ISSUE TITLE
Show all output devices, not just fallback?

### ISSUE THREAD

**Issue by mxmilkiib** [VixenUtils/Myxer#27]
I've two USB DACs and an AV receiver that I go between depending on my needs, but myxer only shows the active fallback device.

How about some day the option to show all output devices?

**Comment by Aurailus** [comment]
Hey there, this would certainly be useful! Unfortunately I don't have time to implement this right now, however if you create a pull request I'd be happy to merge it :) Feel free to reopen if you are interested.

**Comment by Aurailus** [comment]
Hey there, this would certainly be useful! Unfortunately I don't have time to implement this right now, however if you create a pull request I'd be happy to merge it :) Feel free to reopen if you are interested.
