### ISSUE TITLE
Pulseeffects shown as "Unknown"

### ISSUE THREAD

**Issue by danyspin97** [VixenUtils/Myxer#5]
When using pipewire and pulseeffects, Myxer shows `Unknown` instead of `pulseeffects` for both outputs and inputs. Tested with pulseeffects-5.0.3 and pipewire-0.3.25.

**Comment by Aurailus** [comment]
I don't use pipewire, so I was wondering if you could tell me how pulseeffects displays in pavucontrol on your system? That would help me greatly with debugging!

**Comment by DanySpin97** [comment]
It shows `pulseeffects`. Sorry if it wasn't clear from the issue description.

**Comment by Aurailus** [comment]
Ah, I think I have a suspicion as to what might be causing it. I'll take a look this afternoon. Thank you!

**Comment by danyspin97** [comment]
Pulseeffects have been renamed to EasyEffects and now works differently than before. It is not shown as application but as a device, therefore this issue is obsolete.
